project_id = "jlqjdpzsvvmmbbvdboej"

[auth]
enabled = true
site_url = "http://localhost:8080"

[functions.youtube-trending]
verify_jwt = false

[functions.youtube-search]
verify_jwt = false

[functions.youtube-video-details]
verify_jwt = false

[functions.youtube-comments]
verify_jwt = false

[functions.initiate-download]
verify_jwt = true